projects:
  default:
    schema: ./schema.graphql
    extensions:
      endpoints:
        Inexor GraphQL http:
          url: http://localhost:31415/graphql
          introspect: true
        Inexor GraphQL https:
          url: https://localhost:31415/graphql
          introspect: true
