[package]
name = "inexor-rgf-reactive-service-impl"
description = "Inexor - Reactive Graph Flow - Reactive - Model"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
async-trait = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
path-tree = { workspace = true }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
tokio = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-behaviour-model-api = { version = "0.10.0", path = "../../../behaviour/model/api" }
inexor-rgf-behaviour-service-api = { version = "0.10.0", path = "../../../behaviour/service/api" }
inexor-rgf-graph = { version = "0.10.0", path = "../../../graph" }
inexor-rgf-runtime-model = { version = "0.10.0", path = "../../../runtime/model" }
inexor-rgf-model-flow = { version = "0.10.0", path = "../../../model/flow" }
inexor-rgf-reactive-model-api = { version = "0.10.0", path = "../../model/api" }
inexor-rgf-reactive-model-impl = { version = "0.10.0", path = "../../model/impl" }
inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../api" }
inexor-rgf-lifecycle = { version = "0.10.0", path = "../../../lifecycle" }
inexor-rgf-type-system-api = { version = "0.10.0", path = "../../../type-system/api" }

[dev-dependencies]
default-test = { workspace = true }
log4rs = { workspace = true, features = ["console_appender"] }

inexor-rgf-di = { version = "0.10.0", path = "../../../di" }
inexor-rgf-graph = { version = "0.10.0", path = "../../../graph", features = ["test"] }
inexor-rgf-test-utils = { version = "0.10.0", path = "../../../test-utils" }
# Integration tests needs to import the actual implementations
inexor-rgf-type-system-impl = { version = "0.10.0", path = "../../../type-system/impl" }
inexor-rgf-behaviour-service-impl = { version = "0.10.0", path = "../../../behaviour/service/impl" }

[lib]
crate-type = ["lib"]
