[package]
name = "inexor-rgf-core-model"
description = "Inexor - Reactive Graph Flow - Core - Model"
version = "0.6.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
dashmap = "5.1"
indradb-lib = "3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }

inexor-rgf-core-frp = { git = "https://github.com/aschaeffer/inexor-rgf-core-frp.git" }

[dev-dependencies]
random-string = "1.0"
rand = "0.8"
stopwatch2 = "*"

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
