cargo-features = ["edition2021"]

[package]
name = "inexor-rgf-application"
description = "Inexor - Reactive Graph Flow - Application"
version = "0.2.1"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = ["reactive", "graph", "flow", "entity", "entity system", "entity component system", "graph database"]
categories = ["game-engine","entity-component-system","iot","home-automation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.0"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.0.0", features = ["console_appender", "file_appender"]}
uuid = { version = "0.8.2", features = ["serde", "v4"] }
waiter_di = { version = "1.6.4", features = [ "async" ] }
async-trait = "0.1"
async-std = { version = "1.10", features = ["attributes"] }
lazy_static = "1.4.0"
serde = { version = "1.0.130", features = [ "derive" ] }
serde_json = "1.0.67"
indradb-lib = "1"
# TODO: inexor-rgf-plugin-system-env: num_cpus = "1.13.0"
strum = { version = "0.21.0", features = ["derive"] }
strum_macros = "0.21.1"
#syn = "=1.0.57"
syn = "1.0.76"
futures-await-test = "0.3.0"
futures = "0.3"
libloading = "0.7.0"

actix = "0.12"
actix-web = "3"
actix-rt = "2.2.0"
actix-cors = "0.5.4"
actix-files = "0.5.0"
async-graphql = { version = "2.9.14", features = ["uuid"] }
async-graphql-actix-web = "2.9.14"
mime = "0.3.16"

inexor-rgf-core-frp = { git = "https://github.com/aschaeffer/inexor-rgf-core-frp.git" }
inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git" }
inexor-rgf-core-reactive = { git = "https://github.com/aschaeffer/inexor-rgf-core-reactive.git" }
inexor-rgf-core-behaviour = { git = "https://github.com/aschaeffer/inexor-rgf-core-behaviour.git" }
inexor-rgf-core-plugins = { git = "https://github.com/aschaeffer/inexor-rgf-core-plugins.git" }

[[bin]]
name = "inexor-rgf-application"
