cargo-features = [ "workspace-inheritance" ]

[workspace]

members = [
    "crates/core/config",
    "crates/core/di",
    "crates/core/di-codegen",
    "crates/core/builder",
    "crates/model/command",
    "crates/model/dynamic_graph",
    "crates/model/flow",
    "crates/model/runtime",
    "crates/runtime",
    "crates/client",
    "crates/standalone",
]

[workspace.package]
version = "0.9.1"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/inexorgame/inexor-rgf-application"
homepage = "https://inexorgame.github.io/inexor-rgf-application/"
keywords = ["graph", "reactive", "control-flow", "inexor"]

[workspace.dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-http = "3.0"
actix-rt = "2.6"
actix-web = { version = "4.0", features = ["rustls"] }
actix-web-extras = "0.1"
# async-graphql features: uuid, chrono, url, log
async-graphql = { version = "5.0", features = ["uuid", "dynamic-schema"] }
async-graphql-actix-web = { version = "5.0" }
async-trait = "0.1"
async-std = { version = "1.10", features = ["attributes", "tokio1"] }
clap = { version = "4.1", features = ["derive"] }
config = "0.13"
convert_case = "0.6"
crossbeam = "0.8"
cynic = { version = "2.2.8", features = ["http-reqwest"] }
dashmap = "5.3"
futures = "0.3"
futures-timer = "3.0"
futures-util = "0.3"
http = "0.2"
indradb-lib = "3"
json5 = "0.4"
lazy_static = "1.4.0"
libloading = "0.7"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.2", features = ["console_appender", "file_appender", "toml_format", "ansi_writer"] }
mime = "0.3"
notify = "5.0"
num_cpus = "1.15"
paste = "1.0"
path-tree = "0.7"
portpicker = "0.1.1"
proc-macro2 = "1.0"
query_interface = "0.3"
quote = "1.0"
rand = "0.8"
rayon = "1.6"
regex = "1.6"
reqwest = { version = "0.11.14", features = ["json"] }
rust-embed = { version = "6.6", features = ["debug-embed", "compression"] }
rustls = "0.20"
rustls-pemfile = "1.0"
semver = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3.13"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
syn = { version = "1.0", features = [ "full" ] }
tabled = "0.12"
tokio = { version = "1", features =  ["time", "rt"] }
toml = "0.7"
typed-builder = "0.14"
uuid = { version = "1.1", features = ["serde", "v4"] }
walkdir = "2.3"
wildmatch = "2.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
