cargo-features = [ "workspace-inheritance" ]

[workspace]

members = [
    "crates/core/di",
    "crates/core/di-codegen",
    "crates/core/builder",
    "crates/runtime",
    "crates/standalone",
]

[workspace.package]
version = "0.9.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/inexorgame/inexor-rgf-application"

[workspace.dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-http = "3.0"
actix-rt = "2.6"
actix-web = { version = "4.0", features = ["rustls"] }
actix-web-extras = "0.1"
# async-graphql features: uuid, chrono, url, log
async-graphql = { version = "5.0", features = ["uuid", "dynamic-schema"] }
async-graphql-actix-web = { version = "5.0" }
async-trait = "0.1"
async-std = { version = "1.10", features = ["attributes", "tokio1"] }
config = "0.13"
convert_case = "0.6"
crossbeam = "0.8"
dashmap = "5.3"
futures = "0.3"
futures-timer = "3.0"
futures-util = "0.3"
http = "0.2"
indradb-lib = "3"
lazy_static = "1.4.0"
libloading = "0.7"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.2", features = ["console_appender", "file_appender", "toml_format", "ansi_writer"] }
mime = "0.3"
notify = "5.0"
paste = "1.0"
path-tree = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.8"
rayon = "1.6"
regex = "1.6"
rustls = "0.20"
rustls-pemfile = "1.0"
semver = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3.13"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
syn = { version = "1.0", features = [ "full" ] }
tokio = { version = "1", features =  ["time", "rt"] }
toml = "0.5"
uuid = { version = "1.1", features = ["serde", "v4"] }
wildmatch = "2.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
