[package]
name = "inexor-rgf-core-frp"
description = "Inexor - Reactive Graph Flow - Core - FRP (Bidule Patched)"
version = "0.6.0"
authors = [
    "Dimitri Sabadie <dimitri.sabadie@gmail.com>",
    "Andreas Schaeffer <hanack@nooblounge.net",
]
edition = "2021"
license = "BSD-3-Clause"

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
