[package]
name = "inexor-rgf-core-reactive"
description = "Inexor - Reactive Graph Flow - Core - Reactive"
version = "0.4.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
indradb-lib = "1"
log = { version = "0.4", features = ["std", "serde"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
uuid = { version = "0.8", features = ["serde", "v4"] }

inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git", branch = "feature/smaller-dependency-tree" }

[dev-dependencies]
random-string = "1.0"

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
