cargo-features = ["strip"]

[package]
name = "inexor-rgf-application"
description = "Inexor - Reactive Graph Flow - Application"
version = "0.5.1"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = ["reactive", "graph", "flow", "entity", "entity system", "entity component system", "graph database"]
categories = ["game-engine", "entity-component-system", "iot", "home-automation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix = "0.12"
actix-cors = "0.6.0-beta.8"
#actix-files = "0.6.0-beta.15"
actix-http = "3.0.0-beta.19"
actix-rt = "2.6.0"
actix-web = { version = "4.0.0-beta.21" } #, features = ["openssl"]
# async-graphql features: uuid, chrono, url, log
async-graphql = { version = "3.0", features = ["uuid"] }
async-graphql-actix-web = { version = "3.0" }
async-trait = "0.1"
async-std = { version = "1.10", features = ["attributes", "tokio1"] }
crossbeam = "0.8"
futures = "0.3"
#futures-await-test = "0.3.0"
futures-timer = "3.0"
futures-util = "0.3"
indradb-lib = "3"
lazy_static = "1.4.0"
libloading = "0.7"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.0", features = ["console_appender", "file_appender"] }
mime = "0.3"
path-tree = "0.2"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3.13"
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
#syn = "1.0"
tokio = { version = "1", features =  ["time"] }
toml = "0.5"
uuid = { version = "0.8", features = ["serde", "v4"] }

inexor-rgf-core-di = { version = "2.0", features = ["async"], git = "https://github.com/aschaeffer/inexor-rgf-core-di.git" }
inexor-rgf-core-frp = { git = "https://github.com/aschaeffer/inexor-rgf-core-frp.git" }
inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git" }
inexor-rgf-core-builder = { git = "https://github.com/aschaeffer/inexor-rgf-core-builder.git" }
# inexor-rgf-core-reactive = { git = "https://github.com/aschaeffer/inexor-rgf-core-reactive.git" }
inexor-rgf-core-plugins = { git = "https://github.com/aschaeffer/inexor-rgf-core-plugins.git" }

[dev-dependencies]
random-string = "1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
# 12MB -> 7.8MB
lto = true
# 7.8MB -> 4.5MB
strip = "symbols"

[[bin]]
name = "inexor-rgf-application"
