cargo-features = ["edition2021"]

[package]
name = "inexor-rgf-core-bidule"
description = "Inexor - Reactive Graph Flow - Core - Bidule (Patched)"
version = "0.2.1"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
