name: reactive-graph
version: 0.10.0
summary: Reactive Graph
description: Reactive Graph
license: MIT
base: core22
confinement: devmode

parts:
  reactive-graph:
    plugin: rust
    source: .

#  plugins-core:
#    plugin: rust
#    source: https://github.com/reactive-graph/plugins-core.git
#    override-build: |
#      cargo +nightly build --release
#      mkdir $SNAPCRAFT_PART_INSTALL/plugins
#      cp target/release/lib*.so $SNAPCRAFT_PART_INSTALL/plugins/

apps:
  reactive-graph:
    command: bin/reactive-graph
    environment:
      REACTIVE_GRAPH_PLUGINS: $SNAP/plugins
    plugs: [ home ]
