[package]
name = "inexor-rgf-application"
description = "Inexor - Reactive Graph Flow - Application"
version = "0.8.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net>"]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = [
    "reactive",
    "graph",
    "flow",
    "entity",
    "entity system",
    "entity component system",
    "graph database"
]
categories = [
    "desktop-automation",
    "entity-component-system",
    "game-engine",
    "home-automation",
    "iot"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

actix = { workspace = true }
actix-cors = { workspace = true }
actix-http = { workspace = true }
actix-rt = { workspace = true }
actix-web = { workspace = true, features = ["rustls"] }
actix-web-extras = { workspace = true }
# async-graphql features: uuid, chrono, url, log
async-graphql = { workspace = true, features = ["uuid", "dynamic-schema"] }
async-graphql-actix-web = { workspace = true }
async-trait = { workspace = true }
async-std = { workspace = true, features = ["attributes", "tokio1"] }
convert_case = { workspace = true }
crossbeam = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
indradb-lib = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
log4rs = { workspace = true, features = ["console_appender", "file_appender", "toml_format", "ansi_writer"] }
mime = { workspace = true }
notify = { workspace = true }
path-tree = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
signal-hook = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
tokio = { workspace = true, features =  ["time", "rt"] }
toml = { workspace = true }
uuid = { version = "1.1", features = ["serde", "v4"] }
wildmatch = { workspace = true }

inexor-rgf-core-di = { workspace = true }
inexor-rgf-core-frp = { workspace = true }
inexor-rgf-core-model = { workspace = true }
inexor-rgf-core-reactive = { workspace = true }
inexor-rgf-core-builder = { workspace = true }
inexor-rgf-core-plugins = { workspace = true }

[dev-dependencies]
futures-await-test = "0.3"
random-string = "1.0"

[build-dependencies]
build-data = "0.1.3"

[[bin]]
name = "inexor-rgf-application"
