[package]
name = "inexor-rgf-runtime-service-api"
description = "Inexor - Reactive Graph Flow - Runtime - Service - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
async-trait = { workspace = true }
##gql_client = { workspace = true }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

##inexor-rgf-config-model = { version = "0.10.0", path = "../../../config/model" }
##inexor-rgf-graph = { version = "0.10.0", path = "../../../graph" }
##inexor-rgf-command-model = { version = "0.10.0", path = "../../../command/model" }
##inexor-rgf-runtime-model = { version = "0.10.0", path = "../../../runtime/model" }
##inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../../../reactive/service/api" }
inexor-rgf-lifecycle = { version = "0.10.0", path = "../../../lifecycle" }
##inexor-rgf-type-system-api = { version = "0.10.0", path = "../../../type-system/api" }

[lib]
crate-type = ["lib"]
