[package]
name = "inexor-rgf-runtime-web-api"
description = "Inexor - Reactive Graph Flow - Runtime - Web - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
async-trait = { workspace = true }
crossbeam = { workspace = true }
serde = { workspace = true, features = ["derive"] }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
uuid = { workspace = true }

inexor-rgf-lifecycle = { version = "0.10.0", path = "../../../lifecycle" }
inexor-rgf-plugin-api = { version = "0.10.0", path = "../../../plugin/api" }
inexor-rgf-config-api = { version = "0.10.0", path = "../../../config/api" }
inexor-rgf-type-system-api = { version = "0.10.0", path = "../../../type-system/api" }
inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../../../reactive/service/api" }
inexor-rgf-runtime-graphql-api = { version = "0.10.0", path = "../../graphql/api" }
inexor-rgf-plugin-graphql-api = { version = "0.10.0", path = "../../../plugin/graphql/api" }
inexor-rgf-graphql-api = { version = "0.10.0", path = "../../../graphql/api" }
inexor-rgf-dynamic-graph-api = { version = "0.10.0", path = "../../../dynamic-graph/api" }

[lib]
crate-type = ["lib"]
