[package]
name = "inexor-rgf-instance-system-impl"
description = "Inexor - Reactive Graph Flow - Instance System - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
async-trait = { workspace = true }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
uuid = { workspace = true }

inexor-rgf-di = { version = "0.10.0", path = "../../di" }
inexor-rgf-graph = { version = "0.10.0", path = "../../graph" }
inexor-rgf-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
inexor-rgf-instance-system-api = { version = "0.10.0", path = "../api" }
inexor-rgf-plugin-api = { version = "0.10.0", path = "../../plugin/api" }
inexor-rgf-reactive-model-impl = { version = "0.10.0", path = "../../reactive/model/impl" }
inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }

[dev-dependencies]
default-test = { workspace = true }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

inexor-rgf-graph = { version = "0.10.0", path = "../../graph", features = ["test"] }
inexor-rgf-reactive-model-api = { version = "0.10.0", path = "../../reactive/model/api" }
inexor-rgf-test-utils = { version = "0.10.0", path = "../../test-utils" }
# Integration tests needs to import the actual implementations
inexor-rgf-type-system-impl = { version = "0.10.0", path = "../../type-system/impl" }
inexor-rgf-reactive-service-impl = { version = "0.10.0", path = "../../reactive/service/impl" }
inexor-rgf-behaviour-service-impl = { version = "0.10.0", path = "../../behaviour/service/impl" }

[lib]
crate-type = ["lib"]
