[package]
name = "inexor-rgf-client"
description = "Inexor - Reactive Graph Flow - Client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
chrono = { workspace = true }
cynic = { workspace = true, features = ["http-reqwest"] }
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

##inexor-rgf-config-model = { version = "0.10.0", path = "../config/model" }
inexor-rgf-graph = { version = "0.10.0", path = "../graph" }
##inexor-rgf-runtime-model = { version = "0.10.0", path = "../runtime/model" }
inexor-rgf-remotes-model = { version = "0.10.0", path = "../remotes/model" }

[dev-dependencies]
inexor-rgf-runtime-api = { version = "0.10.0", path = "../runtime/api" }
inexor-rgf-runtime-impl = { version = "0.10.0", path = "../runtime/impl" }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

[lib]
crate-type = ["lib"]

[[example]]
name = "list_plugins"

[[example]]
name = "list_remotes"
