[package]
name = "inexor-rgf-client"
description = "Inexor - Reactive Graph Flow - Client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
chrono = { workspace = true }
cynic = { workspace = true, features = ["http-reqwest"] }
lazy_static = { workspace = true }
openssl = { version = "0.10", features = ["vendored"] }
portpicker = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
toml = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-config = { version = "0.10.0", path = "../config" }
inexor-rgf-graph = { version = "0.10.0", path = "../graph" }
inexor-rgf-model-runtime = { version = "0.10.0", path = "../model/runtime" }

[dev-dependencies]
inexor-rgf-rt = { version = "0.10.0", path = "../runtime" }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

[lib]
crate-type = ["lib"]

[[example]]
name = "list_plugins"

[[example]]
name = "list_remotes"
