[package]
name = "inexor-rgf-client"
description = "Inexor - Reactive Graph Flow - Client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
chrono = { workspace = true }
cynic = { workspace = true, features = ["http-reqwest"] }
lazy_static = { workspace = true }
portpicker = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
toml = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-core-config = { version = "0.9.1", path = "../core/config" }
inexor-rgf-core-model = { version = "0.9.1", path = "../core/model" }
inexor-rgf-model-runtime = { version = "0.9.1", path = "../model/runtime" }

[target.'cfg(target = "armv7-unknown-linux-gnueabihf")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target = "aarch64-unknown-linux-gnu")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target = "x86_64-unknown-linux-musl")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[target.'cfg(target = "i686-unknown-linux-musl")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies]
inexor-rgf-rt = { version = "0.9.1", path = "../runtime" }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

[lib]
crate-type = ["lib"]

[[example]]
name = "list_plugins"

[[example]]
name = "list_remotes"
