schema:
  - ./schema_graphql.graphql
  - ./schema_dynamic_graph.graphql
  - ./schema_runtime.graphql
  - ./schema_plugin.graphql
extensions:
  endpoints:
    ReactiveGraph@http:
      url: http://localhost:31415/graphql
      introspect: true
      schema: ./schema_graphql.graphql
    ReactiveGraph@https:
      url: https://localhost:31415/graphql
      introspect: false
      schema: ./schema_graphql.graphql
    DynamicGraph@http:
      url: http://localhost:31415/dynamic_graph
      introspect: true
      schema: ./schema_dynamic_graph.graphql
    DynamicGraph@https:
      url: https://localhost:31415/dynamic_graph
      introspect: false
      schema: ./schema_dynamic_graph.graphql
    ReactiveGraphRuntime@http:
      url: http://localhost:31415/runtime/graphql
      introspect: true
      schema: ./schema_runtime.graphql
    ReactiveGraphRuntime@https:
      url: https://localhost:31415/runtime/graphql
      introspect: false
      schema: ./schema_runtime.graphql
    ReactiveGraphPlugins@http:
      url: http://localhost:31415/plugin/graphql
      introspect: true
      schema: ./schema_plugin.graphql
    ReactiveGraphPlugins@https:
      url: https://localhost:31415/plugin/graphql
      introspect: false
      schema: ./schema_plugin.graphql
