[package]
name = "inexor-rgf-test-utils"
description = "Inexor - Reactive Graph Flow - Test Utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"

[dependencies]
default-test = { workspace = true }
random-string = { workspace = true }
rand = { workspace = true }
rand_derive2 = { workspace = true }
#serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }

#dashmap = { workspace = true, features = [ "serde" ] }
#paste = { workspace = true }
#schemars = { workspace = true, features = [ "uuid1" ] }
#typed-builder = { workspace = true }
#uuid = { workspace = true, features = ["serde", "v4", "v5"] }
#wildmatch = { workspace = true }

#inexor-rgf-core-frp = { version = "0.10.0", path = "../frp" }
#
#[dev-dependencies]
#default-test = { workspace = true }
#random-string = { workspace = true }
#rand = { workspace = true }
#rand_derive2 = { workspace = true }

[lib]
crate-type = ["lib"]
