[package]
name = "inexor-rgf-model-runtime"
description = "Inexor - Reactive Graph Flow - Model - Runtime"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
chrono = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
log4rs = { workspace = true, features = ["console_appender", "file_appender", "toml_format"]}
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
toml = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-core-config = { version = "0.10.0", path = "../../core/config" }
inexor-rgf-core-model = { version = "0.10.0", path = "../../core/model" }
#inexor-rgf-core-builder = { version = "0.10.0", path = "../../core/builder" }

[lib]
crate-type = ["lib"]
