[package]
name = "inexor-rgf-core-di"
description = "Inexor - Reactive Graph Flow - Dependency Injection"
version.workspace = true
authors = [
    "dmitryb.dev@gmail.com",
    "Andreas Schaeffer <hanack@nooblounge.net>"
]
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = [
    "dependency-injection",
    "inversion-of-control",
    "di",
    "ioc"
]

[dependencies]
inexor-rgf-core-di-codegen = { version = "0.9.0", path = "../di-codegen" }
config = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
regex = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }

[features]
async = [ "inexor-rgf-core-di-codegen/async" ]
