[package]
name = "inexor-rgf-core-di"
description = "Inexor - Reactive Graph Flow - Dependency Injection"
version = "2.0.0"
authors = [
    "dmitryb.dev@gmail.com",
    "Andreas Schaeffer <hanack@nooblounge.net>"
]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = [
    "dependency-injection",
    "inversion-of-control",
    "di",
    "ioc"
]
repository = "https://github.com/inexorgame/inexor-rgf-core-di"

[dependencies]
inexor-rgf-core-di-codegen = { path = "../di-codegen" }
config = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
regex = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }

[features]
async = [ "inexor-rgf-core-di-codegen/async" ]
