[package]
name = "reactive-graph-runtime-graphql-schema"
description = "Inexor - Reactive Graph Flow - Runtime - GraphQL - Schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

##reactive-graph-config-model = { version = "0.10.0", path = "../../../config/model" }
reactive-graph-graph = { version = "0.10.0", path = "../../../graph" }
reactive-graph-command-api = { version = "0.10.0", path = "../../../command/api" }
reactive-graph-command-model = { version = "0.10.0", path = "../../../command/model" }
reactive-graph-runtime-model = { version = "0.10.0", path = "../../../runtime/model" }
reactive-graph-runtime-service-api = { version = "0.10.0", path = "../../service/api" }
reactive-graph-remotes-api = { version = "0.10.0", path = "../../../remotes/api" }
reactive-graph-remotes-model = { version = "0.10.0", path = "../../../remotes/model" }

[dev-dependencies]
default-test = { workspace = true }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

reactive-graph-graph = { version = "0.10.0", path = "../../../graph", features = ["test"] }
#reactive-graph-runtime-api = { version = "0.10.0", path = "../../api" }
#reactive-graph-runtime-impl = { version = "0.10.0", path = "../../impl" }
reactive-graph-test-utils = { version = "0.10.0", path = "../../../test-utils" }
reactive-graph-graphql-api = { version = "0.10.0", path = "../../../graphql/api" }

[lib]
crate-type = ["lib"]
