[package]
name = "inexor-rgf-model-command"
description = "Inexor - Reactive Graph Flow - Model - Command"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
clap = { workspace = true, features = ["string"] }
lazy_static = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
log4rs = { workspace = true, features = ["console_appender", "file_appender", "toml_format"]}
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
toml = { workspace = true }
typed-builder = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-graph = { version = "0.10.0", path = "../../graph" }
inexor-rgf-model-runtime = { version = "0.10.0", path = "../runtime" }
inexor-rgf-reactive = { version = "0.10.0", path = "../../reactive" }
inexor-rgf-reactive-api = { version = "0.10.0", path = "../../reactive-api" }

[dev-dependencies]

[lib]
crate-type = ["lib"]
