[package]
name = "inexor-rgf-core-reactive"
description = "Inexor - Reactive Graph Flow - Core - Reactive"
version = "0.8.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
dashmap = "5.4"
indradb-lib = "3"
log = { version = "0.4", features = ["std", "serde"] }
log4rs = { version = "1.0", features = ["console_appender", "file_appender", "toml_format"]}
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
uuid = { version = "1.2", features = ["serde", "v4"] }

# inexor-rgf-core-frp = { git = "https://github.com/inexorgame/inexor-rgf-core-frp.git" }
inexor-rgf-core-frp = { path = "../../../../inexor-rgf-shared-bidule/crates/core/frp" }
# inexor-rgf-core-model = { git = "https://github.com/inexorgame/inexor-rgf-core-model.git" }
inexor-rgf-core-model = { path = "../../../../inexor-rgf-core-model/crates/core/model" }

[dev-dependencies]
random-string = "1.0"

[lib]
crate-type = ["lib"]
