[package]
name = "inexor-rgf-core-reactive"
description = "Inexor - Reactive Graph Flow - Core - Reactive"
version = "0.8.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
dashmap = { workspace = true }
indradb-lib = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
log4rs = { workspace = true, features = ["console_appender", "file_appender", "toml_format"]}
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-core-frp = { path = "../frp" }
inexor-rgf-core-model = { path = "../model" }

[dev-dependencies]
random-string = "1.0"

[lib]
crate-type = ["lib"]
