[package]
name = "inexor-rgf-graphql-api"
description = "Inexor - Reactive Graph Flow - GraphQL - Service - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid"] }
async-trait = { workspace = true }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-graph = { version = "0.10.0", path = "../../graph" }
inexor-rgf-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
inexor-rgf-type-system-api = { version = "0.10.0", path = "../../type-system/api" }
inexor-rgf-graphql-schema = { version = "0.10.0", path = "../schema" }

[lib]
crate-type = ["lib"]
