projects:
  default:
    schema: ./schema.graphql
    extensions:
      endpoints:
        Runtime http:
          url: http://localhost:31415/runtime/graphql
          introspect: true
        Runtime https:
          url: https://localhost:31415/runtime/graphql
          introspect: true
