[package]
name = "inexor-rgf-core-model"
description = "Inexor - Reactive Graph Flow - Core - Model"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
dashmap = { workspace = true }
indradb-lib = { workspace = true }
paste = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v5"] }

inexor-rgf-core-frp = { version = "0.9.0", path = "../frp" }

[dev-dependencies]
random-string = "1.0"
rand = "0.8"
stopwatch2 = "2.0"

[lib]
crate-type = ["lib"]
