[package]
name = "inexor-rgf-remotes-model"
description = "Inexor - Reactive Graph Flow - Remotes - Model"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
typed-builder = { workspace = true }

[lib]
crate-type = ["lib"]
