[build]
rustflags = ["-Z", "threads=8"]

[target.aarch64-unknown-linux-gnu]
objcopy = { path ="aarch64-linux-gnu-objcopy" }
strip = { path ="aarch64-linux-gnu-strip" }
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
objcopy = { path ="arm-none-eabi-objcopy" }
strip = { path ="arm-none-eabi-strip" }
linker = "arm-linux-gnueabihf-gcc"

[target.x86_64-pc-windows-gnu]
objcopy = { path ="x86_64-w64-mingw32-objcopy" }
strip = { path ="x86_64-w64-mingw32-strip" }
linker = "x86_64-w64-mingw32-gcc"
