[package]
name = "inexor-rgf-reactive-model-api"
description = "Inexor - Reactive Graph Flow - Reactive Model - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-graph = { version = "0.10.0", path = "../../../graph" }

[dev-dependencies]
inexor-rgf-test-utils = { version = "0.10.0", path = "../../../test-utils" }

[lib]
crate-type = ["lib"]
