# Scan this file for changes every 30 seconds
refresh_rate = "30 seconds"

[appenders.stdout]
# An appender named "stdout" that writes to stdout
kind = "console"

[appenders.stdout.encoder]
# https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
pattern = "{d(%H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}\r"

[appenders.file-application]
kind = "file"
path = "log/inexor-rgf-application.log"

[appenders.file-application.encoder]
pattern = "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

[appenders.file-errors]
kind = "file"
path = "log/error.log"

[appenders.file-errors.encoder]
pattern = "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

[appenders.file-plugin-connector]
kind = "file"
path = "log/inexor-rgf-plugin-connector.log"

[appenders.file-plugin-connector.encoder]
pattern = "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

[appenders.file-plugin-mqtt]
kind = "file"
path = "log/inexor-rgf-plugin-mqtt.log"

[appenders.file-plugin-mqtt.encoder]
pattern = "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"


# Set the default logging level to "warn" and attach the "stdout" appender to the root
[root]
level = "debug"
appenders = [ "stdout", "file-application" ]

# How to configure the loggers: https://docs.rs/log4rs/1.0.0/log4rs/
[loggers."inexor_rgf_application::implementation::component_manager_impl"]
level = "info"

[loggers."inexor_rgf_application::implementation::entity_vertex_manager_impl"]
level = "info"

[loggers."inexor_rgf_application::implementation::entity_behaviour_manager_impl"]
level = "info"

[loggers."inexor_rgf_application::implementation::relation_behaviour_manager_impl"]
level = "info"

[loggers."inexor_rgf_application::implementation::reactive_flow_manager_impl"]
level = "info"

[loggers."inexor_rgf_plugin_connector::behaviour::relation::relation_behaviour_provider"]
level = "debug"
appenders = [ "file-plugin-connector" ]
additive = false

[loggers."inexor_rgf_plugin_mqtt::provider::component_provider"]
level = "debug"
appenders = [ "file-plugin-mqtt" ]
additive = false

[loggers."inexor_rgf_plugin_mqtt::provider::entity_type_provider"]
level = "debug"
appenders = [ "file-plugin-mqtt" ]
additive = false

[loggers."inexor_rgf_plugin_mqtt::provider::relation_type_provider"]
level = "debug"
appenders = [ "file-plugin-mqtt" ]
additive = false

[loggers."inexor_rgf_plugin_mqtt::behaviour::relation::relation_behaviour_provider"]
level = "debug"
appenders = [ "file-plugin-mqtt" ]
additive = false

[loggers."inexor_rgf_plugin_mqtt::behaviour::relation::mqtt_subscribes"]
level = "debug"
appenders = [ "file-plugin-mqtt" ]
additive = false

[loggers."rumqttc::state"]
level = "debug"
appenders = [ "file-plugin-mqtt" ]
additive = false

[loggers."inexor_rgf_plugin_arithmetic::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_arithmetic::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_base::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_base::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_comparison::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_comparison::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_config::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_config::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_connector::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_connector::provider::relation_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_input_device::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_input_device::provider::relation_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_logical::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_logical::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_numeric::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_numeric::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_system_environment::plugin"]
level = "info"

[loggers."inexor_rgf_plugin_system_environment::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_value::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_string::provider::component_provider"]
level = "info"

[loggers."inexor_rgf_plugin_string::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_json::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_random::provider::entity_type_provider"]
level = "info"

[loggers."inexor_rgf_plugin_http::provider::entity_type_provider"]
level = "info"
