# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      # https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
      pattern: "{d(%H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}\r"

  file-application:
    kind: file
    path: "log/inexor-rgf-application.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

  file-plugin-connector:
    kind: file
    path: "log/inexor-rgf-plugin-connector.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

  file-plugin-mqtt:
    kind: file
    path: "log/inexor-rgf-plugin-mqtt.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: debug
  appenders:
    - stdout
    - file-application

# How to configure the loggers: https://docs.rs/log4rs/1.0.0/log4rs/
loggers:
  inexor_rgf_application::implementation::component_manager_impl:
    level: info
  inexor_rgf_application::implementation::entity_vertex_manager_impl:
    level: info
  inexor_rgf_application::implementation::entity_behaviour_manager_impl:
    level: info
  inexor_rgf_application::implementation::relation_behaviour_manager_impl:
    level: info
  inexor_rgf_application::implementation::reactive_flow_manager_impl:
    level: info
  inexor_rgf_plugin_connector::behaviour::relation::relation_behaviour_provider:
    level: debug
    appenders:
      - file-plugin-connector
    additive: false
  inexor_rgf_plugin_mqtt::provider::component_provider:
    level: debug
    appenders:
      - file-plugin-mqtt
    additive: false
  inexor_rgf_plugin_mqtt::provider::entity_type_provider:
    level: debug
    appenders:
      - file-plugin-mqtt
    additive: false
  inexor_rgf_plugin_mqtt::behaviour::relation::relation_behaviour_provider:
    level: debug
    appenders:
      - file-plugin-mqtt
    additive: false
  inexor_rgf_plugin_mqtt::behaviour::relation::mqtt_subscribes:
    level: debug
    appenders:
      - file-plugin-mqtt
    additive: false
  rumqttc::state:
    level: debug
    appenders:
      - file-plugin-mqtt
    additive: false
