# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      # https://docs.rs/chrono/0.4.11/chrono/format/strftime/index.html
      pattern: "{d(%H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}\r"

  file:
    kind: file
    path: "log/inexor-ecs.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} [{l}] [{T}] {M}:{L} - {m}{n}"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: debug
  appenders:
    - stdout
    - file

loggers:
  inexor_rgf_application::implementation::entity_vertex_manager_impl:
    level: info
  inexor_rgf_application::implementation::entity_behaviour_manager_impl:
    level: info
  inexor_rgf_application::implementation::relation_behaviour_manager_impl:
    level: info
  inexor_rgf_application::implementation::reactive_flow_manager_impl:
    level: info
  inexor_rgf_plugin_connector::behaviour::relation::relation_behaviour_provider:
    level: debug
  inexor_rgf_plugin_mqtt::behaviour::relation::relation_behaviour_provider:
    level: info
  inexor_rgf_plugin_mqtt::behaviour::relation::mqtt_subscribes:
    level: info
  rumqttc::state:
    level: info
