disabled = false

disabled_plugins = [
    # Full name
    # "inexor-rgf-plugin-file",
    # Short name
    # "graphql-schema-visualization"
]

#enabled_plugins = [
#    # Full name
#    "inexor-rgf-plugin-base",
#    # Short name
#    "trigger",
#    "result",
#    "file",
#    "connector",
#    "json",
#    "taxonomy",
#]
