[[plugin]]
name = "inexor-rgf-plugin-base"
active = true
path = "../inexor-rgf-plugin-base/target/debug/libinexor_rgf_plugin_base.so"
# path = "..\\inexor-rgf-plugin-base\\target\\debug\\inexor_rgf_plugin_base.dll"

[[plugin]]
name = "inexor-rgf-plugin-metadata"
active = true
path = "../inexor-rgf-plugin-metadata/target/debug/libinexor_rgf_plugin_metadata.so"

[[plugin]]
name = "inexor-rgf-plugin-taxonomy"
active = true
path = "../inexor-rgf-plugin-taxonomy/target/debug/libinexor_rgf_plugin_taxonomy.so"

[[plugin]]
name = "inexor-rgf-plugin-value"
active = true
path = "../inexor-rgf-plugin-value/target/debug/libinexor_rgf_plugin_value.so"

[[plugin]]
name = "inexor-rgf-plugin-connector"
active = true
path = "../inexor-rgf-plugin-connector/target/debug/libinexor_rgf_plugin_connector.so"

[[plugin]]
name = "inexor-rgf-plugin-numeric"
active = true
path = "../inexor-rgf-plugin-numeric/target/debug/libinexor_rgf_plugin_numeric.so"

[[plugin]]
name = "inexor-rgf-plugin-arithmetic"
active = true
path = "../inexor-rgf-plugin-arithmetic/target/debug/libinexor_rgf_plugin_arithmetic.so"

[[plugin]]
name = "inexor-rgf-plugin-logical"
active = true
path = "../inexor-rgf-plugin-logical/target/debug/libinexor_rgf_plugin_logical.so"

[[plugin]]
name = "inexor-rgf-plugin-comparison"
active = true
path = "../inexor-rgf-plugin-comparison/target/debug/libinexor_rgf_plugin_comparison.so"

[[plugin]]
name = "inexor-rgf-plugin-string"
active = true
path = "../inexor-rgf-plugin-string/target/debug/libinexor_rgf_plugin_string.so"

[[plugin]]
name = "inexor-rgf-plugin-json"
active = true
path = "../inexor-rgf-plugin-json/target/debug/libinexor_rgf_plugin_json.so"

[[plugin]]
name = "inexor-rgf-plugin-binary"
active = true
path = "../inexor-rgf-plugin-binary/target/debug/libinexor_rgf_plugin_binary.so"

[[plugin]]
name = "inexor-rgf-plugin-random"
active = true
path = "../inexor-rgf-plugin-random/target/debug/libinexor_rgf_plugin_random.so"

[[plugin]]
name = "inexor-rgf-plugin-config"
active = true
path = "../inexor-rgf-plugin-config/target/debug/libinexor_rgf_plugin_config.so"

[[plugin]]
name = "inexor-rgf-plugin-system-environment"
active = true
path = "../inexor-rgf-plugin-system-environment/target/debug/libinexor_rgf_plugin_system_environment.so"

[[plugin]]
name = "inexor-rgf-plugin-mqtt"
active = true
path = "../inexor-rgf-plugin-mqtt/target/debug/libinexor_rgf_plugin_mqtt.so"

[[plugin]]
name = "inexor-rgf-plugin-http"
active = true
path = "../inexor-rgf-plugin-http/target/debug/libinexor_rgf_plugin_http.so"

# Linux only (Windows lacks evdev)
[[plugin]]
name = "inexor-rgf-plugin-input-device"
active = true
path = "../inexor-rgf-plugin-input-device/target/debug/libinexor_rgf_plugin_input_device.so"

# Use with caution!
[[plugin]]
name = "inexor-rgf-plugin-system-command"
active = false
path = "../inexor-rgf-plugin-system-command/target/debug/libinexor_rgf_plugin_system_command.so"

# Desktop only
[[plugin]]
name = "inexor-rgf-plugin-notification"
active = false
path = "../inexor-rgf-plugin-notification/target/debug/libinexor_rgf_plugin_notification.so"

[[plugin]]
name = "inexor-rgf-plugin-flow-manager"
active = true
path = "../inexor-rgf-plugin-flow-manager/target/debug/libinexor_rgf_plugin_flow_manager.so"

# Linux only + Desktop only
[[plugin]]
name = "inexor-rgf-plugin-free-desktop"
active = false
path = "../inexor-rgf-plugin-free-desktop/target/debug/libinexor_rgf_plugin_free_desktop.so"

[[plugin]]
name = "inexor-rgf-plugin-tray"
active = false
path = "../inexor-rgf-plugin-tray/target/debug/libinexor_rgf_plugin_tray.so"

[[plugin]]
name = "inexor-rgf-plugin-graphql-schema-visualization"
active = true
path = "../inexor-rgf-plugin-graphql-schema-visualization/target/debug/libinexor_rgf_plugin_graphql_schema_visualization.so"

[[plugin]]
name = "inexor-rgf-plugin-graphql-client"
active = true
path = "../inexor-rgf-plugin-graphql-client/target/debug/libinexor_rgf_plugin_graphql_client.so"


### Plugins in development


[[plugin]]
name = "inexor-rgf-plugin-flow-editor"
active = false
path = "../inexor-rgf-plugin-flow-editor/target/debug/libinexor_rgf_plugin_flow_editor.so"

[[plugin]]
name = "inexor-rgf-plugin-wasm"
active = false
path = "../inexor-rgf-plugin-wasm/target/debug/libinexor_rgf_plugin_wasm.so"

# Linux only
[[plugin]]
name = "inexor-rgf-plugin-fuse"
active = false
path = "../inexor-rgf-plugin-fuse/target/debug/libinexor_rgf_plugin_fuse.so"

[[plugin]]
name = "inexor-rgf-plugin-image-processing"
active = false
path = "../inexor-rgf-plugin-image-processing/target/debug/libinexor_rgf_plugin_image_processing.so"

[[plugin]]
name = "inexor-rgf-plugin-asset"
active = false
path = "../inexor-rgf-plugin-asset/target/debug/libinexor_rgf_plugin_asset.so"
