[[plugin]]
name = "inexor-rgf-plugin-base"
active = true
path = "/home/aschaeffer/CLionProjects/inexor-rgf-plugin-base/target/debug/libinexor_rgf_plugin_base.so"

[[plugin]]
name = "inexor-rgf-plugin-metadata"
active = false
path = "/home/aschaeffer/CLionProjects/inexor-rgf-plugin-metadata/target/debug/libinexor_rgf_plugin_metadata.so"

[[plugin]]
name = "inexor-rgf-plugin-mqtt"
active = false
path = "/home/aschaeffer/CLionProjects/inexor-rgf-plugin-mqtt/target/debug/libinexor_rgf_plugin_mqtt.so"
