[[plugin]]
name = "inexor-rgf-plugin-base"
active = true
path = "../inexor-rgf-plugin-base/target/debug/libinexor_rgf_plugin_base.so"

[[plugin]]
name = "inexor-rgf-plugin-metadata"
active = true
path = "../inexor-rgf-plugin-metadata/target/debug/libinexor_rgf_plugin_metadata.so"

[[plugin]]
name = "inexor-rgf-plugin-taxonomy"
active = true
path = "../inexor-rgf-plugin-taxonomy/target/debug/libinexor_rgf_plugin_taxonomy.so"

[[plugin]]
name = "inexor-rgf-plugin-value"
active = true
path = "../inexor-rgf-plugin-value/target/debug/libinexor_rgf_plugin_value.so"

[[plugin]]
name = "inexor-rgf-plugin-connector"
active = true
path = "../inexor-rgf-plugin-connector/target/debug/libinexor_rgf_plugin_connector.so"

[[plugin]]
name = "inexor-rgf-plugin-numeric"
active = true
path = "../inexor-rgf-plugin-numeric/target/debug/libinexor_rgf_plugin_numeric.so"

[[plugin]]
name = "inexor-rgf-plugin-arithmetic"
active = true
path = "../inexor-rgf-plugin-arithmetic/target/debug/libinexor_rgf_plugin_arithmetic.so"

[[plugin]]
name = "inexor-rgf-plugin-logical"
active = true
path = "../inexor-rgf-plugin-logical/target/debug/libinexor_rgf_plugin_logical.so"

[[plugin]]
name = "inexor-rgf-plugin-comparison"
active = true
path = "../inexor-rgf-plugin-comparison/target/debug/libinexor_rgf_plugin_comparison.so"

[[plugin]]
name = "inexor-rgf-plugin-config"
active = true
path = "../inexor-rgf-plugin-config/target/debug/libinexor_rgf_plugin_config.so"

[[plugin]]
name = "inexor-rgf-plugin-system-environment"
active = true
path = "../inexor-rgf-plugin-system-environment/target/debug/libinexor_rgf_plugin_system_environment.so"

[[plugin]]
name = "inexor-rgf-plugin-mqtt"
active = true
path = "../inexor-rgf-plugin-mqtt/target/debug/libinexor_rgf_plugin_mqtt.so"

[[plugin]]
name = "inexor-rgf-plugin-input-device"
active = true
path = "../inexor-rgf-plugin-input-device/target/debug/libinexor_rgf_plugin_input_device.so"

[[plugin]]
name = "inexor-rgf-plugin-flow-editor"
active = true
path = "../inexor-rgf-plugin-flow-editor/target/debug/libinexor_rgf_plugin_flow_editor.so"
