[[remotes]]
hostname = "demo.rgf.app"
port = 443
secure = true

[[remotes]]
hostname = "localhost"
port = 31416
userAgent = "Noob Agent"

[[remotes]]
hostname = "localhost"
port = 31417

[[remotes]]
hostname = "localhost"
port = 31418
