[package]
name = "inexor-rgf-graphql-impl"
description = "Inexor - Reactive Graph Flow - GraphQL - Service - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
async-graphql = { workspace = true, features = ["uuid"] }
async-trait = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-di = { version = "0.10.0", path = "../../di" }
inexor-rgf-graph = { version = "0.10.0", path = "../../graph" }
inexor-rgf-graphql-schema = { version = "0.10.0", path = "../schema" }
inexor-rgf-graphql-api = { version = "0.10.0", path = "../api" }
inexor-rgf-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
inexor-rgf-type-system-api = { version = "0.10.0", path = "../../type-system/api" }
inexor-rgf-behaviour-service-api = { version = "0.10.0", path = "../../behaviour/service/api" }
inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }

[dev-dependencies]
default-test = { workspace = true }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

inexor-rgf-graph = { version = "0.10.0", path = "../../graph", features = ["test"] }
inexor-rgf-runtime-api = { version = "0.10.0", path = "../../runtime/api" }
inexor-rgf-runtime-impl = { version = "0.10.0", path = "../../runtime/impl" }
inexor-rgf-test-utils = { version = "0.10.0", path = "../../test-utils" }

[lib]
crate-type = ["lib"]
