[package]
name = "reactive-graph-runtime-service-impl"
description = "Reactive Graph - Runtime - Service - Implementation"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../../README.md"

[dependencies]
async-trait = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
springtime-di = { workspace = true, features = ["threadsafe", "derive"] }
tokio = { workspace = true } # , features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"]
toml = { workspace = true }

reactive-graph-graph = { version = "0.10.0", path = "../../../graph" }
reactive-graph-lifecycle = { version = "0.10.0", path = "../../../lifecycle" }
reactive-graph-runtime-service-api = { version = "0.10.0", path = "../api" }
reactive-graph-command-model = { version = "0.10.0", path = "../../../command/model" }
reactive-graph-runtime-model = { version = "0.10.0", path = "../../../runtime/model" }
reactive-graph-reactive-model-api = { version = "0.10.0", path = "../../../reactive/model/api" }
reactive-graph-reactive-model-impl = { version = "0.10.0", path = "../../../reactive/model/impl" }
reactive-graph-reactive-service-api = { version = "0.10.0", path = "../../../reactive/service/api" }

[dev-dependencies]
default-test = { workspace = true }
tokio = { workspace = true, features = ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

reactive-graph-test-utils = { version = "0.10.0", path = "../../../test-utils" }

[lib]
crate-type = ["lib"]
