[package]
name = "inexor-rgf-core-builder"
description = "Inexor - Reactive Graph Flow - Core - Builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
indradb-lib = { workspace = true }
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4"] }

inexor-rgf-core-model = { path = "../model" }

[dev-dependencies]
random-string = "1.0"

[lib]
crate-type = ["lib"]
