[package]
name = "inexor-rgf-core-builder"
description = "Inexor - Reactive Graph Flow - Core - Builder"
version = "0.8.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
indradb-lib = "3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
uuid = { version = "1.2", features = ["serde", "v4"] }

#inexor-rgf-core-model = { git = "https://github.com/inexorgame/inexor-rgf-core-model.git" }
inexor-rgf-core-model = { path = "../../../../inexor-rgf-core-model/crates/core/model" }

[dev-dependencies]
random-string = "1.0"

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
# 12MB -> 7.8MB
lto = true
# 7.8MB -> 4.5MB
strip = "symbols"
# 4.5MB -> 3.7MB
# opt-level = "z"
