[package]
name = "inexor-rgf-core-frp"
description = "Inexor - Reactive Graph Flow - Core - FRP (Bidule Patched)"
version = "0.7.0"
authors = [
    "Dimitri Sabadie <dimitri.sabadie@gmail.com>",
    "Andreas Schaeffer <hanack@nooblounge.net",
]
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
log = { workspace = true, features = ["std", "serde"] }
log4rs = { workspace = true, features = ["console_appender", "file_appender", "toml_format"]}
rayon = { workspace = true }
uuid = { workspace = true, features = ["fast-rng", "v4"]}

[lib]
crate-type = ["lib"]
