[package]
name = "reactive-graph-reactive-derive"
description = "Inexor - Reactive Graph Flow - Reactive - Derive Macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = [ "full" ] }

[lib]
proc-macro = true
