[package]
name = "inexor-rgf-runtime-api"
description = "Inexor - Reactive Graph Flow - Runtime - API"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"
keywords = [
    "reactive",
    "graph",
    "flow",
    "entity-system",
    "ecs"
]
categories = [
    "desktop-automation",
    "entity-component-system",
    "game-engine",
    "home-automation",
    "iot"
]

[dependencies]
async-trait = { workspace = true }
springtime-di = { workspace = true, features = [ "threadsafe", "derive" ] }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

inexor-rgf-lifecycle = { version = "0.10.0", path = "../../lifecycle" }
inexor-rgf-config-api = { version = "0.10.0", path = "../../config/api" }
inexor-rgf-config-model = { version = "0.10.0", path = "../../config/model" }
inexor-rgf-type-system-api = { version = "0.10.0", path = "../../type-system/api" }
inexor-rgf-instance-system-api = { version = "0.10.0", path = "../../instance-system/api" }
inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }
inexor-rgf-behaviour-service-api = { version = "0.10.0", path = "../../behaviour/service/api" }
inexor-rgf-runtime-service-api = { version = "0.10.0", path = "../service/api" }
inexor-rgf-runtime-graphql-api = { version = "0.10.0", path = "../graphql/api" }
inexor-rgf-runtime-web-api = { version = "0.10.0", path = "../web/api" }
inexor-rgf-graphql-api = { version = "0.10.0", path = "../../graphql/api" }
inexor-rgf-dynamic-graph-api = { version = "0.10.0", path = "../../dynamic-graph/api" }
inexor-rgf-plugin-service-api = { version = "0.10.0", path = "../../plugin/service/api" }
inexor-rgf-plugin-graphql-api = { version = "0.10.0", path = "../../plugin/graphql/api" }
inexor-rgf-command-api = { version = "0.10.0", path = "../../command/api" }
inexor-rgf-remotes-api = { version = "0.10.0", path = "../../remotes/api" }
inexor-rgf-remotes-model = { version = "0.10.0", path = "../../remotes/model" }

[dev-dependencies]

[features]
test = []

[lib]
crate-type = ["lib"]
