[package]
name = "inexor-rgf-graphql-schema"
description = "Inexor - Reactive Graph Flow - GraphQL - Schema"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../../README.md"

[dependencies]
async-trait = { workspace = true }
async-graphql = { workspace = true, features = ["uuid"] }
crossbeam = { workspace = true }
futures-timer = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true, features = ["std", "serde"] }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
uuid = { workspace = true }

inexor-rgf-graph = { version = "0.10.0", path = "../../graph" }
inexor-rgf-runtime-model = { version = "0.10.0", path = "../../runtime/model" }
inexor-rgf-reactive-model-api = { version = "0.10.0", path = "../../reactive/model/api" }
inexor-rgf-reactive-model-impl = { version = "0.10.0", path = "../../reactive/model/impl" }
inexor-rgf-reactive-service-api = { version = "0.10.0", path = "../../reactive/service/api" }
inexor-rgf-behaviour-model-api = { version = "0.10.0", path = "../../behaviour/model/api" }
inexor-rgf-behaviour-service-api = { version = "0.10.0", path = "../../behaviour/service/api" }
inexor-rgf-type-system-api = { version = "0.10.0", path = "../../type-system/api" }

[dev-dependencies]
colored = { workspace = true }
default-test = { workspace = true }
glob = { workspace = true }
similar = { workspace = true }
similar-asserts = { workspace = true }
tokio = { workspace = true, features =  ["macros", "time", "rt", "rt-multi-thread", "test-util"] }

inexor-rgf-graph = { version = "0.10.0", path = "../../graph", features = ["test"] }
inexor-rgf-runtime-api = { version = "0.10.0", path = "../../runtime/api" }
inexor-rgf-runtime-impl = { version = "0.10.0", path = "../../runtime/impl" }
inexor-rgf-test-utils = { version = "0.10.0", path = "../../test-utils" }
# TODO: compile runtime with graphql, but without plugin system, dynamic graph, ...!

[lib]
crate-type = ["lib"]
