name: Feature Branch
run-name: Feature Branch ${{ github.ref_name }}

on:
  push:
    branches:
      - "feature/*.*.*/**"

permissions:
  pull-requests: write

jobs:
  feature-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        run: gh pr create --base main --head ${{github.ref}} --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
