name: Feature Branch
run-name: Feature Branch ${{ github.ref_name }}

on:
  push:
    branches:
      - "feature/*.*.*/**"

permissions:
  pull-requests: write

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        run: gh pr create -B 'main' -f --reviewer 'reactive-graph/code-contributors'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
