name: Feature Branch PR
run-name: Create a Pull Request for Feature Branch ${{ github.ref_name }}

on:
  push:
    branches:
      - "feature/*.*.*/**"

permissions:
  pull-requests: write

jobs:
  create_pr_repo_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_reviewer: "reactive-graph/code-contributors"
          github_token: '${{ secrets.GITHUB_TOKEN }}'
