name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/lint.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: clippy
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
