name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/lint.yml"

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-08-19
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
