name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Tier 1
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          # Tier 1
          # - target: x86_64-unknown-linux-musl
          #   os: ubuntu-latest
          # Tier 1
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          # Tier 2
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
          # Tier 1
          - target: x86_64-apple-darwin
            os: macos-latest
          # Tier 2
          - target: aarch64-apple-darwin
            os: macos-latest
          # Universal macOS binary is supported as universal-apple-darwin.
          - target: universal-apple-darwin
            os: macos-latest
          # Tier 1
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          # - target: x86_64-pc-windows-gnu
          #   os: ubuntu-latest
          # Tier 2
          # - target: aarch64-pc-windows-msvc
          #   os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      # Required by arm targets
      - name: Install packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pkg-config openssl libssl-dev
          version: 1.1
        if: matrix.os == 'ubuntu-latest'
      - name: Upload Rust Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: reactive-graph
          target: ${{ matrix.target }}
          include: LICENSE.md,README.md,CHANGELOG.md,config,plugins
          tar: unix
          zip: windows
          leading_dir: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VERGEN_IDEMPOTENT: true
  crates-io:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Cargo Workspaces
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-workspaces
          version: latest
          use-tool-cache: true
      - name: Publish on crates.io
        uses: actions-rs/cargo@v1
        with:
          command: workspaces
          args: publish --from-git
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          VERGEN_IDEMPOTENT: true
  debian-package:
    name: Publish debian package
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            # libc 2.31
            os: ubuntu-20.04
          - target: aarch64-unknown-linux-gnu
            # libc 2.31
            os: ubuntu-20.04
          - target: armv7-unknown-linux-gnueabihf
            # libc 2.31
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Get version number from git tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1
        with:
          strip_v: true
      - name: Install aarch64 packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
          version: 1.0
        if: matrix.target == 'aarch64-unknown-linux-gnu'
      - name: Install armv7 packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: binutils-arm-none-eabi gcc-arm-linux-gnueabihf
          version: 1.0
        if: matrix.target == 'armv7-unknown-linux-gnueabihf'
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Cargo Deb
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-deb
          version: latest
          use-tool-cache: true
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Create Debian Package
        run: |
          cd ./crates/reactive-graph
          cargo deb -p reactive-graph --target=${{ matrix.target }} --deb-version ${{steps.tag.outputs.tag}}
        env:
          VERGEN_IDEMPOTENT: true
      - name: Upload debian package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/debian/reactive-graph_*_*.deb
          file_glob: true
          tag: ${{ github.ref }}
