name: Remove Labels

on:
  issues:
    types: [ closed ]
  pull_request:
    types: [ closed ]

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "good first issue, help wanted, question"
