name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  AWS_LC_SYS_PREBUILT_NASM: 1

jobs:
  formatting:
    name: Verify code formatting
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install latest nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-08-19
          components: rustfmt
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [ stable, nightly-2024-08-19 ]
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl ]
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Run cargo clippy
        run: cargo clippy
  build:
    name: Build in release mode
    needs: [ formatting, lint ]
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        toolchain: [ stable, nightly-2024-08-19 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Build (Release Mode)
        run: cargo build --release --verbose
  test:
    name: Test Suite
    needs: [ formatting, lint ]
    strategy:
      matrix:
        toolchain: [ stable, nightly-2024-08-19 ]
        target: [ x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl ]
    runs-on: ubuntu-latest
    steps:
      - name: VCS Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.5
      - name: Test (Release Mode)
        run: cargo test --release --verbose --target ${{ matrix.target }}
